name: Django CI - Password-Generator - Ruben

on:
  push:
    branches: [ "develop", "main" ]
  pull_request:
    branches: [ "develop", "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      sonarqube:
        image: sonarqube:latest
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl --fail http://localhost:9000/api/system/health || exit 1" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    strategy:
      max-parallel: 4
      matrix:
        python-version: [ 3.12 ]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        run: python manage.py test

      - name: Wait for SonarQube to be ready
        run: |
          for i in {1..10}; do
            curl -s http://localhost:9000/api/system/health && exit 0 || sleep 10;
          done
          exit 1

      - name: Run SonarQube Scanner
        run: |
          docker run -e SONAR_HOST_URL=http://localhost:9000 \
            -e SONAR_TOKEN=${{ secrets.SONAR_TOKEN }} \
            sonarsource/sonar-scanner-cli \
            -Dsonar.projectKey=Password-Generator \
            -Dsonar.sources=.